pipeline {

    agent any

    environment {
        NETWORK_NAME = "taskflow-network"

        DB_CONTAINER = "taskflow-db"
        DB_IMAGE = "taskflow-db:latest"
        DB_VOLUME = "taskflow-db-data"

        BACKEND_CONTAINER = "taskflow-backend"
        BACKEND_IMAGE = "taskflow-backend:latest"

        FRONTEND_CONTAINER = "taskflow-frontend"
        FRONTEND_IMAGE = "taskflow-frontend:latest"

        DB_NAME = "taskapp"
        DB_USER = "taskuser"

        BACKEND_PORT = "4000"
        FRONTEND_PORT = "3000"
    }

    stages {

        // --------------------------------------------------
        // 1. CHECKOUT
        // --------------------------------------------------

        stage('Checkout') {
            steps {
                checkout scm
            }
        }
        
        
        // --------------------------------------------------
        // 10. BUILD FRONTEND
        // --------------------------------------------------

        stage('Build Frontend Image') {
            steps {
                sh '''
                    echo "Building frontend image..."

                    docker build \
                        -t ${FRONTEND_IMAGE} \
                        ./frontend

                    docker rm -f ${FRONTEND_CONTAINER} 2>/dev/null || true

                    docker run -d \
                        --name ${FRONTEND_CONTAINER} \
                        -p ${FRONTEND_PORT}:80 \
                        ${FRONTEND_IMAGE}
                '''
            }
        }


        stage('Start Backend') {
            steps {
                sh '''
                    docker build \
                        -t ${BACKEND_IMAGE} \
                        ./backend

                    docker rm -f ${BACKEND_CONTAINER} 2>/dev/null || true

                    docker run -d \
                        --name ${BACKEND_CONTAINER} \
                        -p ${BACKEND_PORT}:4000 \
                        ${BACKEND_IMAGE}
                '''
            }
        }


        // --------------------------------------------------
        // BUILD DATABASE IMAGE
        // --------------------------------------------------

        stage('Build Database Image') {
            steps {
                sh '''
                    echo "Building PostgreSQL image..."

                    docker build \
                        -t ${DB_IMAGE} \
                        ./database
                '''
            }
        }


        // --------------------------------------------------
        // 4. START DATABASE
        // --------------------------------------------------

        stage('Start PostgreSQL') {
            steps {

                withCredentials([
                    string(
                        credentialsId: 'taskflow-db-password',
                        variable: 'DB_PASSWORD'
                    )
                ]) {
                    sh '''
                        echo "Starting PostgreSQL..."

                        docker run -d \
                            --name ${DB_CONTAINER} \
                            --network ${NETWORK_NAME} \
                            -e POSTGRES_DB=${DB_NAME} \
                            -e POSTGRES_USER=${DB_USER} \
                            -e POSTGRES_PASSWORD="$DB_PASSWORD" \
                            -v ${DB_VOLUME}:/var/lib/postgresql \
                            ${DB_IMAGE}
                    '''
                }
            }
        }
    }
}
